=== dfkibasys/basyx-v3-client-libraries/tests/testschema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "name" : {
            "type": "string"
        },
        "comment" : {
            "type": "string"
        },
        "initialState": {
            "type": "object",
            "properties": {
                "shells": {
                    "type": "array",
                    "items": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/AssetAdministrationShell"
                    }
                },
                "submodels": {
                    "type": "array",
                    "items": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/Submodel"
                    }
                },
                "shellDescriptors": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0.1#/components/schemas/AssetAdministrationShellDescriptor"
                    }
                },
                "submodelDescriptors": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0.1#/components/schemas/SubmodelDescriptor"
                    }
                }
            }
        },
        "invocation": {
            "type": "object",
            "properties": {
                "args": {
                    "type": "object"
                }
            },
            "required": ["args"]
        },
        "expectedState": {
            "type": "object",
            "properties": {
                "shells": {
                    "type": "array",
                    "items": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/AssetAdministrationShell"
                    }
                },
                "submodels": {
                    "type": "array",
                    "items": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/Submodel"
                    }
                },
                "shellDescriptors": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0.1#/components/schemas/AssetAdministrationShellDescriptor"
                    }
                },
                "submodelDescriptors": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0.1#/components/schemas/SubmodelDescriptor"
                    }
                }
            }
        },
        "expectedReturnValue": {
            "type": "object"
        },
        "expectedErrorStatusCode": {
            "type": "integer",
            "pattern": "^(4|5)\\d{2}$"
        }
    },
    "oneOf": [
        {
            "required": ["expectedReturnValue"]
        },
        {
            "required": ["expectedErrorStatusCode"]
        }
    ],
    "required": ["expectedState"]
}

=== dfkibasys/basyx-v3-client-libraries/tests/submodel-repository/getFileAttachment_404_attachment.json
{
    "name": "attachment-not-found (404)",
    "initialState": {
            "submodels": [
                {
                    "modelType": "Submodel",
                    "kind": "Instance",
                    "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                    "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                    "submodelElements": []
                },
                {
                    "modelType": "Submodel",
                    "kind": "Instance",
                    "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                    "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                    "submodelElements":  [ 
                        {
                            "modelType" : "File",
                            "idShort" : "BasyxImage",
                            "value" : "basyx_thumbnail.png",
                            "contentType": "image/png"
                        }
                    ]
                }
            ],
            "fileAttachments" : {
            }
    },
    "invocation": {
        "args": {
            "submodelIdentifier": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
            "idShortPath": "BasyxImage"
        }
    },
    "expectedState": {
        "submodels": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                "submodelElements":  [ 
                    {
                        "modelType" : "File",
                        "idShort" : "BasyxImage",
                        "value" : "basyx_thumbnail.png",
                        "contentType": "image/png"
                    }
                ]
            }
        ],
        "fileAttachments" : {
        }
    },
    "expectedErrorStatusCode" : 404
}

=== dfkibasys/basyx-v3-client-libraries/tests/aas-repository/postSubmodelReference_409.json
{
    "name": "conflict-test 409",
    "initialState": {
        "shells": [
            {
                "modelType": "AssetAdministrationShell",
                "assetInformation": {
                    "assetKind": "Instance",
                    "globalAssetId": "https://acplt.org/Test_Asset"
                },
                "submodels": [
                    {
                        "keys": [
                            {
                                "type": "Submodel",
                                "value": "http://acplt.org/Submodels/Assets/TestAsset/BillOfMaterial"
                            }
                        ],
                        "type": "ExternalReference"
                    }
                ],
                "id": "https://acplt.org/Test_AssetAdministrationShell",
                "idShort": "TestAssetAdministrationShell"
            }
        ],
        "submodels": []
    },
    "invocation": {
        "args": {
            "aasIdentifier": "https://acplt.org/Test_AssetAdministrationShell",
            "reference": {
                "keys": [
                    {
                        "type": "Submodel",
                        "value": "http://acplt.org/Submodels/Assets/TestAsset/BillOfMaterial"
                    }
                ],
                "type": "ExternalReference"
            }
        }
    },
    "comment": "Just overridden, no conflict but also no duplicates",
    "expectedState": {
        "shells": [
            {
                "modelType": "AssetAdministrationShell",
                "assetInformation": {
                    "assetKind": "Instance",
                    "globalAssetId": "https://acplt.org/Test_Asset"
                },
                "submodels": [
                    {
                        "keys": [
                            {
                                "type": "Submodel",
                                "value": "http://acplt.org/Submodels/Assets/TestAsset/BillOfMaterial"
                            }
                        ],
                        "type": "ExternalReference"
                    }
                ],
                "id": "https://acplt.org/Test_AssetAdministrationShell",
                "idShort": "TestAssetAdministrationShell"
            }
        ]
    },
    "expectedErrorStatusCode": 409
}

=== dfkibasys/basyx-v3-client-libraries/tests/submodel-repository/getAllSubmodels_limit.json
{
    "name": "limit-test",
    "initialState": {
        "submodels": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40_Erdgas",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40_Erdgas",
                "submodelElements": []
            }
        ]
    },
    "invocation": {
        "args": {
            "limit" : 2
        }
    },
    "expectedState": {
        "submodels": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40_Erdgas",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40_Erdgas",
                "submodelElements": []
            }
        ]
    },
    "expectedReturnValue": {
        "paging_metadata": {
            "cursor" : "aHR0cDovL3NtLnR3aW5maWNpZW50LmRlL1RlY2huaWNhbERhdGEvaGVhdGVyLWRlZmluaXRpb24vT3B0aW1hX1BsdXNfNDA"
        },
        "result": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                "submodelElements": []
            }
        ]
    }
}

=== dfkibasys/basyx-v3-client-libraries/tests/aas-repository/postAssetAdministrationShell_409.json
{
    "name": "conflict-test 409",
    "initialState": {
        "shells": [
            {
                "modelType": "AssetAdministrationShell",
                "assetInformation": {
                    "assetKind": "Instance",
                    "globalAssetId": "https://acplt.org/Test_Asset"
                },
                "derivedFrom": {
                    "keys": [
                        {
                            "type": "AssetAdministrationShell",
                            "value": "https://acplt.org/TestAssetAdministrationShell2"
                        }
                    ],
                    "type": "ExternalReference"
                },
                "submodels": [
                    {
                        "keys": [
                            {
                                "type": "Submodel",
                                "value": "https://acplt.org/Test_Submodel"
                            }
                        ],
                        "type": "ExternalReference"
                    },
                    {
                        "keys": [
                            {
                                "type": "Submodel",
                                "value": "http://acplt.org/Submodels/Assets/TestAsset/BillOfMaterial"
                            }
                        ],
                        "type": "ExternalReference"
                    },
                    {
                        "keys": [
                            {
                                "type": "Submodel",
                                "value": "http://acplt.org/Submodels/Assets/TestAsset/Identification"
                            }
                        ],
                        "type": "ExternalReference"
                    }
                ],
                "administration": {
                    "revision": "9",
                    "version": "0"
                },
                "id": "https://acplt.org/Test_AssetAdministrationShell",
                "description": [
                    {
                        "language": "en-us",
                        "text": "An Example Asset Administration Shell for the test application"
                    },
                    {
                        "language": "de",
                        "text": "Ein Beispiel-Verwaltungsschale für eine Test-Anwendung"
                    }
                ],
                "idShort": "TestAssetAdministrationShell"
            }
        ],
        "submodels": []
    },
    "invocation": {
        "args": {
            "assetAdministrationShell" :             {
                "modelType": "AssetAdministrationShell",
                "assetInformation": {
                    "assetKind": "Instance",
                    "globalAssetId": "https://acplt.org/Test_Asset"
                },
                "derivedFrom": {
                    "keys": [
                        {
                            "type": "AssetAdministrationShell",
                            "value": "https://acplt.org/TestAssetAdministrationShell2"
                        }
                    ],
                    "type": "ExternalReference"
                },
                "submodels": [
                    {
                        "keys": [
                            {
                                "type": "Submodel",
                                "value": "https://acplt.org/Test_Submodel"
                            }
                        ],
                        "type": "ExternalReference"
                    },
                    {
                        "keys": [
                            {
                                "type": "Submodel",
                                "value": "http://acplt.org/Submodels/Assets/TestAsset/BillOfMaterial"
                            }
                        ],
                        "type": "ExternalReference"
                    },
                    {
                        "keys": [
                            {
                                "type": "Submodel",
                                "value": "http://acplt.org/Submodels/Assets/TestAsset/Identification"
                            }
                        ],
                        "type": "ExternalReference"
                    }
                ],
                "administration": {
                    "revision": "10",
                    "version": "0"
                },
                "id": "https://acplt.org/Test_AssetAdministrationShell",
                "idShort": "ToUpdate"
            }
        }
    },
    "expectedState": {
        "shells": [
            {
                "modelType": "AssetAdministrationShell",
                "assetInformation": {
                    "assetKind": "Instance",
                    "globalAssetId": "https://acplt.org/Test_Asset"
                },
                "derivedFrom": {
                    "keys": [
                        {
                            "type": "AssetAdministrationShell",
                            "value": "https://acplt.org/TestAssetAdministrationShell2"
                        }
                    ],
                    "type": "ExternalReference"
                },
                "submodels": [
                    {
                        "keys": [
                            {
                                "type": "Submodel",
                                "value": "https://acplt.org/Test_Submodel"
                            }
                        ],
                        "type": "ExternalReference"
                    },
                    {
                        "keys": [
                            {
                                "type": "Submodel",
                                "value": "http://acplt.org/Submodels/Assets/TestAsset/BillOfMaterial"
                            }
                        ],
                        "type": "ExternalReference"
                    },
                    {
                        "keys": [
                            {
                                "type": "Submodel",
                                "value": "http://acplt.org/Submodels/Assets/TestAsset/Identification"
                            }
                        ],
                        "type": "ExternalReference"
                    }
                ],
                "administration": {
                    "revision": "9",
                    "version": "0"
                },
                "id": "https://acplt.org/Test_AssetAdministrationShell",
                "description": [
                    {
                        "language": "en-us",
                        "text": "An Example Asset Administration Shell for the test application"
                    },
                    {
                        "language": "de",
                        "text": "Ein Beispiel-Verwaltungsschale für eine Test-Anwendung"
                    }
                ],
                "idShort": "TestAssetAdministrationShell"
            }
        ],
        "submodels": []
    },
    "expectedErrorStatusCode": 409
}

=== dfkibasys/basyx-v3-client-libraries/tests/submodel-repository/getSubmodelByIdMetadata_404.json
{
    "name": "not-found-test (404)",
    "initialState": {
        "submodels": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40_Erdgas",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40_Erdgas",
                "submodelElements": []
            }
        ]
    },
    "invocation": {
        "args": {
            "submodelIdentifier": "https://admin-shell.io/idta/TimeSeries/1/1_2"
        }
    },
    "expectedState": {
        "submodels": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40_Erdgas",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40_Erdgas",
                "submodelElements": []
            }
        ]
    },
    "expectedErrorStatusCode": 404
}

=== dfkibasys/basyx-v3-client-libraries/tests/submodel-repository/putSubmodelElement_404_path.json
{
    "name": "path-not-found-test (404)",
    "initialState": {
        "submodels": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                "submodelElements": {
                    "modelType": "SubmodelElementCollection",
                    "idShort": "col1",
                    "value": [
                        {
                            "modelType": "SubmodelElementCollection",
                            "idShort": "inner",
                            "value": []
                        }
                    ]
                }
            }
        ]
    },
    "invocation": {
        "args": {
            "submodelIdentifier": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
            "idShortPath": "col1.unknown",
            "submodelElement": {
                "modelType": "Property",
                "value": "12",
                "valueType": "xs:integer",
                "idShort": "inner"
            }
        }
    },
    "expectedState": {
        "submodels": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                "submodelElements": {
                    "modelType": "SubmodelElementCollection",
                    "idShort": "col1",
                    "value": [
                        {
                            "modelType": "SubmodelElementCollection",
                            "idShort": "inner",
                            "value": []
                        }
                    ]
                }
            }
        ]
    },
    "expectedErrorStatusCode" : 404
}

=== dfkibasys/basyx-v3-client-libraries/tests/submodel-repository/postSubmodelElementByPath.json
{
    "name": "success-test",
    "initialState": {
        "submodels": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                "submodelElements": {
                    "modelType": "SubmodelElementCollection",
                    "idShort": "col1",
                    "value": [
                        {
                            "modelType": "SubmodelElementCollection",
                            "idShort": "col2"
                        }
                    ]
                }
            }
        ]
    },
    "invocation": {
        "args": {
            "submodelIdentifier": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
            "idShortPath": "col1.col2",
            "submodelElement": {
                "modelType": "Property",
                "value": "12",
                "valueType": "xs:integer",
                "idShort": "prop1"
            }
        }
    },
    "expectedState": {
        "submodels": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                "submodelElements": {
                    "modelType": "SubmodelElementCollection",
                    "idShort": "col1",
                    "value": [
                        {
                            "modelType": "SubmodelElementCollection",
                            "idShort": "col2",
                            "value": [
                                {
                                    "modelType": "Property",
                                    "value": "12",
                                    "valueType": "xs:integer",
                                    "idShort": "prop1"
                                }
                            ]
                        }
                    ]
                }
            }
        ]
    },
    "expectedReturnValue": {
        "modelType": "Property",
        "value": "12",
        "valueType": "xs:integer",
        "idShort": "Prop1"
    }
}
