=== dfkibasys/basyx-v3-client-libraries/tests/testschema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "name" : {
            "type": "string"
        },
        "comment" : {
            "type": "string"
        },
        "initialState": {
            "type": "object",
            "properties": {
                "shells": {
                    "type": "array",
                    "items": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/AssetAdministrationShell"
                    }
                },
                "submodels": {
                    "type": "array",
                    "items": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/Submodel"
                    }
                },
                "shellDescriptors": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0.1#/components/schemas/AssetAdministrationShellDescriptor"
                    }
                },
                "submodelDescriptors": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0.1#/components/schemas/SubmodelDescriptor"
                    }
                }
            }
        },
        "invocation": {
            "type": "object",
            "properties": {
                "args": {
                    "type": "object"
                }
            },
            "required": ["args"]
        },
        "expectedState": {
            "type": "object",
            "properties": {
                "shells": {
                    "type": "array",
                    "items": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/AssetAdministrationShell"
                    }
                },
                "submodels": {
                    "type": "array",
                    "items": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/Submodel"
                    }
                },
                "shellDescriptors": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0.1#/components/schemas/AssetAdministrationShellDescriptor"
                    }
                },
                "submodelDescriptors": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0.1#/components/schemas/SubmodelDescriptor"
                    }
                }
            }
        },
        "expectedReturnValue": {
            "type": "object"
        },
        "expectedErrorStatusCode": {
            "type": "integer",
            "pattern": "^(4|5)\\d{2}$"
        }
    },
    "oneOf": [
        {
            "required": ["expectedReturnValue"]
        },
        {
            "required": ["expectedErrorStatusCode"]
        }
    ],
    "required": ["expectedState"]
}

=== dfkibasys/basyx-v3-client-libraries/tests/submodel-service/postSubmodelElement.json
{
    "name": "success-test",
    "initialState": {
        "submodelServiceElements": [
            {
                "modelType": "Property",
                "value": "123",
                "idShort": "test"
            },
            {
                "modelType": "Operation",
                "inputVariables": [
                    {
                        "value": {
                            "modelType": "Property",
                            "valueType": "xs:int",
                            "idShort": "input"
                        }
                    }
                ],
                "outputVariables": [
                    {
                        "value": {
                            "modelType": "Property",
                            "valueType": "xs:int",
                            "idShort": "result"
                        }
                    }
                ],
                "idShort": "HelloOperation"
            },
            {
                "modelType": "SubmodelElementCollection",
                "idShort": "BaseOperations",
                "value": [
                    {
                        "modelType": "Operation",
                        "idShort": "AddOperation",
                        "inputVariables": [
                            {
                                "value": {
                                    "modelType": "Property",
                                    "valueType": "xs:string",
                                    "idShort": "request"
                                }
                            }
                        ],
                        "outputVariables": [
                            {
                                "value": {
                                    "modelType": "Property",
                                    "valueType": "xs:string",
                                    "idShort": "result"
                                }
                            }
                        ]
                    }
                ]
            }
        ]
    },
    "invocation": {
        "args": {
            "submodelElement": {
                "modelType": "Property",
                "value": "2",
                "idShort": "test2"
            }
        }
    },
    "expectedState": {
        "submodelServiceElements": [
            {
                "modelType": "Property",
                "value": "55",
                "idShort": "test"
            },
            {
                "modelType": "Property",
                "value": "2",
                "idShort": "test2"
            },
            {
                "modelType": "Operation",
                "inputVariables": [
                    {
                        "value": {
                            "modelType": "Property",
                            "valueType": "xs:int",
                            "idShort": "input"
                        }
                    }
                ],
                "outputVariables": [
                    {
                        "value": {
                            "modelType": "Property",
                            "valueType": "xs:int",
                            "idShort": "result"
                        }
                    }
                ],
                "idShort": "HelloOperation"
            },
            {
                "modelType": "SubmodelElementCollection",
                "idShort": "BaseOperations",
                "value": [
                    {
                        "modelType": "Operation",
                        "idShort": "AddOperation",
                        "inputVariables": [
                            {
                                "value": {
                                    "modelType": "Property",
                                    "valueType": "xs:string",
                                    "idShort": "request"
                                }
                            }
                        ],
                        "outputVariables": [
                            {
                                "value": {
                                    "modelType": "Property",
                                    "valueType": "xs:string",
                                    "idShort": "result"
                                }
                            }
                        ]
                    }
                ]
            }
        ]
    },
    "expectedReturnValue": {
        "modelType": "Property",
        "value": "2",
        "idShort": "test2"
    }
}

=== dfkibasys/basyx-v3-client-libraries/tests/aas-discoveryservice/getAllShellIdsByAssetLinks_cursor_and_limit.json
{
    "name": "success-test-cursor-and-limit",
    "initialState": {
        "assetLinks": {
            "https://acplt.org/Test:AssetAdministrationShell1": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test1"
                },
                {
                    "name": "type",
                    "value": "robot"
                }
            ],
            "https://acplt.org/Test:AssetAdministrationShell2": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test2"
                },
                {
                    "name": "type",
                    "value": "heater"
                }
            ],
            "https://acplt.org/Test:AssetAdministrationShell3": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test3"
                },
                {
                    "name": "type",
                    "value": "robot"
                }
            ]
        }
    },
    "invocation": {
        "args": {
            "limit": 2,
            "cursor" : "aHR0cHM6Ly9hY3BsdC5vcmcvVGVzdF9Bc3NldEFkbWluaXN0cmF0aW9uU2hlbGwy"
        }
    },
    "expectedState": {
        "assetLinks": {
            "https://acplt.org/Test AssetAdministrationShell1": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test1"
                },
                {
                    "name": "type",
                    "value": "robot"
                }
            ],
            "https://acplt.org/Test AssetAdministrationShell2": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test2"
                },
                {
                    "name": "type",
                    "value": "heater"
                }
            ],
            "https://acplt.org/Test AssetAdministrationShell3": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test3"
                },
                {
                    "name": "type",
                    "value": "robot"
                }
            ]
        }
    },
    "expectedReturnValue": {
        "paging_metadata": {
        },
        "result": [
            "https://acplt.org/Test AssetAdministrationShell3"
        ]
    }
}

=== dfkibasys/basyx-v3-client-libraries/tests/aas-discoveryservice/getAllShellIdsByAssetLinks_limit.json
{
    "name": "success-test-limit",
    "initialState": {
        "assetLinks": {
            "https://acplt.org/Test_AssetAdministrationShell1": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test1"
                },
                {
                    "name": "type",
                    "value": "robot"
                }
            ],
            "https://acplt.org/Test_AssetAdministrationShell2": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test2"
                },
                {
                    "name": "type",
                    "value": "heater"
                }
            ],
            "https://acplt.org/Test_AssetAdministrationShell3": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test3"
                },
                {
                    "name": "type",
                    "value": "robot"
                }
            ]
        }
    },
    "invocation": {
        "args": {
            "limit": 2
        }
    },
    "expectedState": {
        "assetLinks": {
            "https://acplt.org/Test_AssetAdministrationShell1": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test1"
                },
                {
                    "name": "type",
                    "value": "robot"
                }
            ],
            "https://acplt.org/Test_AssetAdministrationShell2": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test2"
                },
                {
                    "name": "type",
                    "value": "heater"
                }
            ],
            "https://acplt.org/Test_AssetAdministrationShell3": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test3"
                },
                {
                    "name": "type",
                    "value": "robot"
                }
            ]
        }
    },
    "expectedReturnValue": {
        "paging_metadata": {
            "cursor": "aHR0cHM6Ly9hY3BsdC5vcmcvVGVzdF9Bc3NldEFkbWluaXN0cmF0aW9uU2hlbGwy"
        },
        "result": [
            "https://acplt.org/Test_AssetAdministrationShell1",
            "https://acplt.org/Test_AssetAdministrationShell2"
        ]
    }
}

=== dfkibasys/basyx-v3-client-libraries/tests/aas-discoveryservice/getAllShellIdsByAssetLinks_filtered.json
{
    "name": "filtered-test",
    "initialState": {
        "assetLinks": {
            "https://acplt.org/Test_AssetAdministrationShell1": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test1"
                },
                {
                    "name": "type",
                    "value": "robot"
                }
            ],
            "https://acplt.org/Test_AssetAdministrationShell2": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test2"
                },
                {
                    "name": "type",
                    "value": "heater"
                }
            ],
            "https://acplt.org/Test_AssetAdministrationShell3": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test3"
                },
                {
                    "name": "type",
                    "value": "robot"
                }
            ]
        }
    },
    "invocation": {
        "args": {
            "assetIds": [
                {
                    "name": "type",
                    "value": "robot"
                }
            ]
        }
    },
    "expectedState": {
        "assetLinks": {
            "https://acplt.org/Test_AssetAdministrationShell1": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test1"
                },
                {
                    "name": "type",
                    "value": "robot"
                }
            ],
            "https://acplt.org/Test_AssetAdministrationShell2": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test2"
                },
                {
                    "name": "type",
                    "value": "heater"
                }
            ],
            "https://acplt.org/Test_AssetAdministrationShell3": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test3"
                },
                {
                    "name": "type",
                    "value": "robot"
                }
            ]
        }
    },
    "expectedReturnValue": {
        "paging_metadata": {},
        "result": [
            "https://acplt.org/Test_AssetAdministrationShell1",
            "https://acplt.org/Test_AssetAdministrationShell3"
        ]
    }
}

=== dfkibasys/basyx-v3-client-libraries/tests/submodel-service/getAllSubmodelElements.json
{
    "name": "success-test",
    "initialState": {
        "submodelServiceElements": [
            {
                "modelType": "SubmodelElementCollection",
                "idShort": "BaseOperations",
                "value": [
                    {
                        "modelType": "Operation",
                        "idShort": "AddOperation",
                        "inputVariables": [
                            {
                                "value": {
                                    "modelType": "Property",
                                    "valueType": "xs:string",
                                    "idShort": "request"
                                }
                            }
                        ],
                        "outputVariables": [
                            {
                                "value": {
                                    "modelType": "Property",
                                    "valueType": "xs:string",
                                    "idShort": "result"
                                }
                            }
                        ]
                    }
                ]
            },
            {
                "modelType": "Operation",
                "inputVariables": [
                    {
                        "value": {
                            "modelType": "Property",
                            "valueType": "xs:int",
                            "idShort": "input"
                        }
                    }
                ],
                "outputVariables": [
                    {
                        "value": {
                            "modelType": "Property",
                            "valueType": "xs:int",
                            "idShort": "result"
                        }
                    }
                ],
                "idShort": "HelloOperation"
            },
            {
                "modelType": "Property",
                "value": "123",
                "idShort": "test"
            }
        ]
    },
    "invocation": {
        "args": {}
    },
    "expectedState": {
        "submodelServiceElements": [
            {
                "modelType": "SubmodelElementCollection",
                "idShort": "BaseOperations",
                "value": [
                    {
                        "modelType": "Operation",
                        "idShort": "AddOperation",
                        "inputVariables": [
                            {
                                "value": {
                                    "modelType": "Property",
                                    "valueType": "xs:string",
                                    "idShort": "request"
                                }
                            }
                        ],
                        "outputVariables": [
                            {
                                "value": {
                                    "modelType": "Property",
                                    "valueType": "xs:string",
                                    "idShort": "result"
                                }
                            }
                        ]
                    }
                ]
            },
            {
                "modelType": "Operation",
                "inputVariables": [
                    {
                        "value": {
                            "modelType": "Property",
                            "valueType": "xs:int",
                            "idShort": "input"
                        }
                    }
                ],
                "outputVariables": [
                    {
                        "value": {
                            "modelType": "Property",
                            "valueType": "xs:int",
                            "idShort": "result"
                        }
                    }
                ],
                "idShort": "HelloOperation"
            },
            {
                "modelType": "Property",
                "value": "123",
                "idShort": "test"
            }
        ]
    },
    "expectedReturnValue": {
        "paging_metadata" : { },
        "result": [
            {
                "modelType": "SubmodelElementCollection",
                "idShort": "BaseOperations",
                "value": [
                    {
                        "modelType": "Operation",
                        "idShort": "AddOperation",
                        "inputVariables": [
                            {
                                "value": {
                                    "modelType": "Property",
                                    "valueType": "xs:string",
                                    "idShort": "request"
                                }
                            }
                        ],
                        "outputVariables": [
                            {
                                "value": {
                                    "modelType": "Property",
                                    "valueType": "xs:string",
                                    "idShort": "result"
                                }
                            }
                        ]
                    }
                ]
            },
            {
                "modelType": "Operation",
                "inputVariables": [
                    {
                        "value": {
                            "modelType": "Property",
                            "valueType": "xs:int",
                            "idShort": "input"
                        }
                    }
                ],
                "outputVariables": [
                    {
                        "value": {
                            "modelType": "Property",
                            "valueType": "xs:int",
                            "idShort": "result"
                        }
                    }
                ],
                "idShort": "HelloOperation"
            },
            {
                "modelType": "Property",
                "value": "123",
                "idShort": "test"
            }
        ]
    }
}

=== dfkibasys/basyx-v3-client-libraries/tests/aas-discoveryservice/postAssetLinksByShellId_409.json
{
    "name": "conflict-test (409)",
    "initialState": {
        "assetLinks" : {
            "https://acplt.org/Test_AssetAdministrationShell": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test"
                },
                {
                    "name": "type",
                    "value": "robot"
                }
            ]
        }
    },
    "invocation": {
        "args": {
            "aasIdentifier": "https://acplt.org/Test_AssetAdministrationShell",
            "specificAssetId": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test"
                },
                {
                    "name": "type",
                    "value": "robot"
                }
            ]
        }
    },
    "expectedState": {
        "assetLinks" : {
            "https://acplt.org/Test_AssetAdministrationShell": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test"
                },
                {
                    "name": "type",
                    "value": "robot"
                }
            ]
        }
    },
    "expectedErrorStatusCode": 409
}

=== dfkibasys/basyx-v3-client-libraries/tests/submodel-repository/getSubmodelById.json
{
    "name": "success-test",
    "initialState": {
        "submodels": [
            
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40_Erdgas",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40_Erdgas",
                "submodelElements": []
            }
        ]
    },
    "invocation": {
        "args": {
            "submodelIdentifier" : "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30"
        }
    },
    "expectedState": {
        "submodels": [            
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40_Erdgas",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40_Erdgas",
                "submodelElements": []
            }
        ]
    },
    "expectedReturnValue" : {
        "modelType": "Submodel",
        "kind": "Instance",
        "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
        "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
        "submodelElements": []
    }
}

=== dfkibasys/basyx-v3-client-libraries/tests/submodel-repository/getAllSubmodels.json
{
    "name": "success-test",
    "initialState": {
        "submodels": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40_Erdgas",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40_Erdgas",
                "submodelElements": []
            }
        ]
    },
    "invocation": {
        "args": {}
    },
    "expectedState": {
        "submodels": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40_Erdgas",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40_Erdgas",
                "submodelElements": []
            }
        ]
    },
    "expectedReturnValue": {
        "paging_metadata": {},
        "result": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40_Erdgas",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40_Erdgas",
                "submodelElements": []
            }
        ]
    }
}
