=== dfkibasys/basyx-v3-client-libraries/tests/testschema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "name" : {
            "type": "string"
        },
        "comment" : {
            "type": "string"
        },
        "initialState": {
            "type": "object",
            "properties": {
                "shells": {
                    "type": "array",
                    "items": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/AssetAdministrationShell"
                    }
                },
                "submodels": {
                    "type": "array",
                    "items": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/Submodel"
                    }
                },
                "shellDescriptors": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0.1#/components/schemas/AssetAdministrationShellDescriptor"
                    }
                },
                "submodelDescriptors": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0.1#/components/schemas/SubmodelDescriptor"
                    }
                }
            }
        },
        "invocation": {
            "type": "object",
            "properties": {
                "args": {
                    "type": "object"
                }
            },
            "required": ["args"]
        },
        "expectedState": {
            "type": "object",
            "properties": {
                "shells": {
                    "type": "array",
                    "items": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/AssetAdministrationShell"
                    }
                },
                "submodels": {
                    "type": "array",
                    "items": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/Submodel"
                    }
                },
                "shellDescriptors": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0.1#/components/schemas/AssetAdministrationShellDescriptor"
                    }
                },
                "submodelDescriptors": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0.1#/components/schemas/SubmodelDescriptor"
                    }
                }
            }
        },
        "expectedReturnValue": {
            "type": "object"
        },
        "expectedErrorStatusCode": {
            "type": "integer",
            "pattern": "^(4|5)\\d{2}$"
        }
    },
    "oneOf": [
        {
            "required": ["expectedReturnValue"]
        },
        {
            "required": ["expectedErrorStatusCode"]
        }
    ],
    "required": ["expectedState"]
}

=== dfkibasys/basyx-v3-client-libraries/tests/submodel-repository/putFileAttachment_404_path.json
{
    "name": "sme-path-not-found (404)",
    "initialState": {
            "submodels": [
                {
                    "modelType": "Submodel",
                    "kind": "Instance",
                    "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                    "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                    "submodelElements": []
                },
                {
                    "modelType": "Submodel",
                    "kind": "Instance",
                    "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                    "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                    "submodelElements":  [ 
                        {
                            "modelType" : "File",
                            "idShort" : "BasyxImage",
                            "value" : "basyx_thumbnail.png",
                            "contentType": "image/png"
                        }
                    ]
                }
            ]
    },
    "invocation": {
        "args": {
            "submodelIdentifier": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
            "idShortPath": "UnknownPath",
            "fileName": "basyx_thumbnail.png",
            "_file": "$PROPERTY(basyxtest.folder)/basyx_thumbnail.png"
        }
    },
    "expectedState": {
        "submodels": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                "submodelElements":  [ 
                    {
                        "modelType" : "File",
                        "idShort" : "BasyxImage",
                        "contentType" : "image/png"
                    }
                ]
            }
        ],
        "fileAttachments" : {
        }
    },
    "expectedErrorStatusCode" : 404
}

=== dfkibasys/basyx-v3-client-libraries/tests/submodel-repository/getAllSubmodelElements_limit.json
{
    "name": "success-test-limit",
    "initialState": {
        "submodels": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": [
                    {
                        "modelType": "Property",
                        "value": "1",
                        "valueType": "xs:long",
                        "idShort": "1"
                    },
                    {
                        "modelType": "Property",
                        "value": "2",
                        "valueType": "xs:long",
                        "idShort": "2"
                    },
                    {
                        "modelType": "Property",
                        "value": "3",
                        "valueType": "xs:long",
                        "idShort": "3"
                    },
                    {
                        "modelType": "Property",
                        "value": "4",
                        "valueType": "xs:long",
                        "idShort": "4"
                    },
                    {
                        "modelType": "Property",
                        "value": "5",
                        "valueType": "xs:long",
                        "idShort": "5"
                    }
                ]
            }
        ]
    },
    "invocation": {
        "args": {
            "submodelIdentifier": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
            "limit": 2
        }
    },
    "expectedState": {
        "submodels": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": [
                    {
                        "modelType": "Property",
                        "value": "1",
                        "valueType": "xs:long",
                        "idShort": "1"
                    },
                    {
                        "modelType": "Property",
                        "value": "2",
                        "valueType": "xs:long",
                        "idShort": "2"
                    },
                    {
                        "modelType": "Property",
                        "value": "3",
                        "valueType": "xs:long",
                        "idShort": "3"
                    },
                    {
                        "modelType": "Property",
                        "value": "4",
                        "valueType": "xs:long",
                        "idShort": "4"
                    },
                    {
                        "modelType": "Property",
                        "value": "5",
                        "valueType": "xs:long",
                        "idShort": "5"
                    }
                ]
            }
        ]
    },
    "expectedReturnValue": {
        "paging_metadata": {
            "cursor" : "Mg"
        },
        "result": [
            {
                "modelType": "Property",
                "value": "1",
                "valueType": "xs:long",
                "idShort": "1"
            },
            {
                "modelType": "Property",
                "value": "2",
                "valueType": "xs:long",
                "idShort": "2"
            }
        ]
    }
}

=== dfkibasys/basyx-v3-client-libraries/tests/aas-registry/getAllAssetAdministrationShellDescriptors_empty.json
{
    "name": "empty-test",
    "initialState": {
        "shells": [],
        "submodels": []
    },
    "invocation": {
        "args": {}
    },
    "expectedState": {
        "shells": [],
        "submodels": []
    },
    "expectedReturnValue": {
        "paging_metadata": {},
        "result": []
    }
}

=== dfkibasys/basyx-v3-client-libraries/tests/submodel-repository/getAllSubmodelElements_limit_cursor.json
{
    "name": "success-test-limit-and-cursor",
    "initialState": {
        "submodels": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": [
                    {
                        "modelType": "Property",
                        "value": "1",
                        "valueType": "xs:long",
                        "idShort": "1"
                    },
                    {
                        "modelType": "Property",
                        "value": "2",
                        "valueType": "xs:long",
                        "idShort": "2"
                    },
                    {
                        "modelType": "Property",
                        "value": "3",
                        "valueType": "xs:long",
                        "idShort": "3"
                    },
                    {
                        "modelType": "Property",
                        "value": "4",
                        "valueType": "xs:long",
                        "idShort": "4"
                    },
                    {
                        "modelType": "Property",
                        "value": "5",
                        "valueType": "xs:long",
                        "idShort": "5"
                    }
                ]
            }
        ]
    },
    "invocation": {
        "args": {
            "submodelIdentifier": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
            "limit": 4,
            "cursor": "Mg"
        }
    },
    "expectedState": {
        "submodels": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": [
                    {
                        "modelType": "Property",
                        "value": "1",
                        "valueType": "xs:long",
                        "idShort": "1"
                    },
                    {
                        "modelType": "Property",
                        "value": "2",
                        "valueType": "xs:long",
                        "idShort": "2"
                    },
                    {
                        "modelType": "Property",
                        "value": "3",
                        "valueType": "xs:long",
                        "idShort": "3"
                    },
                    {
                        "modelType": "Property",
                        "value": "4",
                        "valueType": "xs:long",
                        "idShort": "4"
                    },
                    {
                        "modelType": "Property",
                        "value": "5",
                        "valueType": "xs:long",
                        "idShort": "5"
                    }
                ]
            }
        ]
    },
    "expectedReturnValue": {
        "paging_metadata": { 
        },
        "result": [
            {
                "modelType": "Property",
                "value": "3",
                "valueType": "xs:long",
                "idShort": "3"
            },
            {
                "modelType": "Property",
                "value": "4",
                "valueType": "xs:long",
                "idShort": "4"
            },
            {
                "modelType": "Property",
                "value": "5",
                "valueType": "xs:long",
                "idShort": "5"
            }
        ]
    }
}

=== dfkibasys/basyx-v3-client-libraries/tests/submodel-repository/postSubmodel_409.json
{
    "name": "conflict-test 409",
    "initialState": {
        "submodels": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                "submodelElements": []
            }
        ]
    },
    "invocation": {
        "args": {
            "submodel": {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                "submodelElements": []
            }
        }
    },
    "expectedState": {
        "submodels": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                "submodelElements": []
            }
        ]
    },
    "expectedErrorStatusCode": 409
}

=== dfkibasys/basyx-v3-client-libraries/tests/aas-repository/postSubmodelReferenceAasRepository_409.json
{
    "name": "conflict-test 409",
    "initialState": {
        "shells": [
            {
                "modelType": "AssetAdministrationShell",
                "assetInformation": {
                    "assetKind": "Instance",
                    "globalAssetId": "https://acplt.org/Test_Asset"
                },
                "submodels": [
                    {
                        "keys": [
                            {
                                "type": "Submodel",
                                "value": "http://acplt.org/Submodels/Assets/TestAsset/BillOfMaterial"
                            }
                        ],
                        "type": "ExternalReference"
                    }
                ],
                "id": "https://acplt.org/Test_AssetAdministrationShell",
                "idShort": "TestAssetAdministrationShell"
            }
        ],
        "submodels": []
    },
    "invocation": {
        "args": {
            "aasIdentifier": "https://acplt.org/Test_AssetAdministrationShell",
            "reference": {
                "keys": [
                    {
                        "type": "Submodel",
                        "value": "http://acplt.org/Submodels/Assets/TestAsset/BillOfMaterial"
                    }
                ],
                "type": "ExternalReference"
            }
        }
    },
    "expectedState": {
        "shells": [
            {
                "modelType": "AssetAdministrationShell",
                "assetInformation": {
                    "assetKind": "Instance",
                    "globalAssetId": "https://acplt.org/Test_Asset"
                },
                "submodels": [
                    {
                        "keys": [
                            {
                                "type": "Submodel",
                                "value": "http://acplt.org/Submodels/Assets/TestAsset/BillOfMaterial"
                            }
                        ],
                        "type": "ExternalReference"
                    }
                ],
                "id": "https://acplt.org/Test_AssetAdministrationShell",
                "idShort": "TestAssetAdministrationShell"
            }
        ]
    },
    "expectedReturnValue": {
        "keys": [
            {
                "type": "Submodel",
                "value": "http://acplt.org/Submodels/Assets/TestAsset/BillOfMaterial"
            }
        ],
        "type": "ExternalReference"
    }
}

=== dfkibasys/basyx-v3-client-libraries/tests/submodel-repository/patchSubmodelElementValue_404_smid.json
{
    "name": "success-test (string)",
    "initialState": {
        "submodels": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                "submodelElements": [{
                        "modelType": "Property",
                        "value": "12",
                        "valueType": "xs:integer",
                        "idShort": "prop"
                    }
                ]
            }
        ]
    },
    "invocation": {
        "args": {
            "submodelIdentifier": "http://sm.twinficient.de/TechnicalData/heater-definition/Unknown",
            "idShortPath": "prop",
            "submodelElementValue": "13"
        }
    },
    "expectedState": {
        "submodels": [
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_30",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_30",
                "submodelElements": []
            },
            {
                "modelType": "Submodel",
                "kind": "Instance",
                "id": "http://sm.twinficient.de/TechnicalData/heater-definition/Optima_Plus_40",
                "idShort": "TechnicalData-heater-definition/Optima_Plus_40",
                "submodelElements": [
                    {
                        "modelType": "Property",
                        "value": "12",
                        "valueType": "xs:integer",
                        "idShort": "prop"
                    }
                ]
            }
        ]
    },
    "expectedErrorStatusCode" : 404
}

=== dfkibasys/basyx-v3-client-libraries/tests/aas-discoveryservice/deleteAssetLinksByShellId_404.json
{
    "name": "not-found-test (404)",
    "initialState": {
        "assetLinks" : {
            "https://acplt.org/Test_AssetAdministrationShell": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test"
                },
                {
                    "name": "type",
                    "value": "robot"
                }
            ]
        }
    },
    "invocation": {
        "args": {
            "aasIdentifier": "https://acplt.org/Unknown"
        }
    },
    "expectedState": {
        "assetLinks" : {
            "https://acplt.org/Test_AssetAdministrationShell": [
                {
                    "name": "specificAssetId",
                    "value": "org::acplt::asset::test"
                },
                {
                    "name": "type",
                    "value": "robot"
                }
            ]
        }
    },
    "expectedErrorStatusCode" : 404
}
